title: BUAA-Dreamer'Blog 
description: This is the personal blog of BUAA-Dreamer.
show_downloads: false
excerpt_description: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://buaadreamer.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Dreamer
image: /thumbnail-jumbo.png
twitter:
  username: Dreamer

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['articles', 'about', 'contact']
